name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  build_test_lint:
    uses: ./.github/workflows/ci.yml
  publish:
    runs-on: ubuntu-latest
    needs: build_test_lint
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
